version: 2.1
jobs:
  build:
    parallelism: 1
    machine:
    - image: ubuntu-2004:202101-01
    working_directory: ~/xiph/ezstream
    shell: /bin/bash --login
    steps:
    - checkout
    - run: sudo apt-get install gettext lcov check libshout-dev libtagc0-dev libxml2-dev
    - run: ./autogen.sh
    - run: ./configure
    - run: make distcheck distclean
    - run: ./configure CFLAGS='-O0 -fprofile-arcs -ftest-coverage -fstack-protector-all'
    - run: make check
    - run: mkdir coverage
    - run: lcov --capture --output-file coverage/ezstream.lcov --rc lcov_branch_coverage=1 --directory src --test-name ezstream
    - run: make distclean
    - run: bash <(curl -s https://codecov.io/bash)
